language: c
env:
    - CFLAGS="-fprofile-arcs -ftest-coverage"
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get install -y lcov
    - gem install coveralls-lcov
script:
    - make
    - make test
    - ./runecos
    - ./runecosexp
    - ./ecostester
    - ./ecos_bb_test
after_success:
    - lcov --compat-libtool --directory . --capture --output-file coverage.info
    - coveralls-lcov coverage.info
notifications:
  slack: embotech:Slv0KoBZrsrG2Bl7OAT407FT
